### ISSUE TITLE
Remove the unused parameters in request body

### ISSUE THREAD

**Issue by freesky-edward** [huawei-clouds/terraform-provider-telefonicaopencloud#10]
Sent some unused parameter when creating auto-scaling policy

### Terraform Version
0.11.0

### Affected Resource(s)
- autoscaling policy
- ces

### Terraform Configuration Files
resource "telefonicaopencloud_as_group_v1" "hth_asg"{
  scaling_group_name = "hth_asg"
  scaling_configuration_id = "${telefonicaopencloud_as_configuration_v1.hth_asconfig.id}"
  desire_instance_number = 2
  min_instance_number = 0
  max_instance_number = 3
  networks = [
    {id = "${var.subnet_id}"},
  ]
  security_groups = [
    {id = "${var.security_group_id}"},
  ]
  vpc_id = "${var.vpc_id}"
  delete_publicip = true
  delete_instances = "yes" 
}

resource "telefonicaopencloud_as_policy_v1" "hth_aspolicy"{
  scaling_policy_name = "hth_aspolicy"
  scaling_group_id = "${telefonicaopencloud_as_group_v1.hth_asg.id}"
  scaling_policy_type = "RECURRENCE"
  scaling_policy_action = {
    operation = "ADD"
	instance_number = 1
  }
  alarm_id = al1516347655071WZPeOj4ZO
}

resource "telefonicaopencloud_as_configuration_v1" "hth_asconfig"{
  scaling_configuration_name = "hth_asgconfig"
  instance_config = {
    flavor = "${var.flavor}"
    image = "${var.image_id}"
    disk = [
      {size = 40
      volume_type = "SATA"
      disk_type = "SYS"}
    ]
    key_name = "${var.keyname}"
    user_data = "${file("userdata.txt")}"
  }
}

### Debug log
 2018/01/19 15:46:33 [DEBUG] OpenStack Request URL: POST https://as.eu-preprod.telefonicaopencloud.com/autoscaling-api/v1/0e182ee7fbab414eaf9e3bf92a89500d/scaling_policy
 2018/01/19 15:46:33 [DEBUG] Openstack Request Headers:
 Accept: application/json
 Content-Type: application/json
 User-Agent: Terraform 0.10.0-dev (go1.8.1) gophercloud/2.0.0
 X-Auth-Token: ***
 2018/01/19 15:46:33 [DEBUG] OpenStack Request Body: {
   "alarm_id": "al1516347655071WZPeOj4ZO",
   "cool_down_time": 900,
   "scaling_group_id": "99cb0d66-1282-46b7-bef1-4724a547267f",
   "scaling_policy_action": {
     "instance_number": 1,
     "operation": "ADD"
   },
   "scaling_policy_name": "lzh_aspolicy",
   "scaling_policy_type": "ALARM",
   **"scheduled_policy": {
     "launch_time": ""
   }**
 }

though it works well now, it would be more better to not send the unused parameters.

**Comment by freesky-edward** [comment]
@niuzhenguo I am not sure is it necessary  to update this kind of enhancement. it seems it can work well now, the only thing is it doesn't match the interface definition. your comments are appreciated .

**Comment by niuzhenguo** [comment]
@freesky-edward Agree, should change to use omitempty, but need @h00130372 to confirm this.

**Comment by freesky-edward** [comment]
@niuzhenguo thanks
