### ISSUE TITLE
ASG with elb_backendecs 

### ISSUE THREAD

**Issue by Joncak** [huawei-clouds/terraform-provider-telefonicaopencloud#24]
Hi, there's a way to add a Autoscaling Group behid a loadbalancer backendecs, the resource need the private_address but the variable is not exported on the as_group.

I also try with telefonicaopencloud_compute_instance_v2 but cannot add the lb_listener_id argument to the resource.

### Affected Resource(s)
- telefonicaopencloud_as_group_v1
- telefonicaopencloud_elb_loadbalance
- telefonicaopencloud_elb_backendecs
- telefonicaopencloud_compute_instance_v2

**Comment by niuzhenguo** [comment]
@Joncak Thanks for the bug report!
@zengchen1024 Can you please help to check out this?

**Comment by zengchen1024** [comment]
@Joncak Please see the [here](https://github.com/huawei-clouds/terraform-provider-telefonicaopencloud/blob/master/website/docs/r/as_group_v1.html.markdown#autoscaling-group-with-elb-listener). It may help you.

**Comment by Joncak** [comment]
thanks @zengchen1024 i don't need the the telefonicaopencloud_elb_backendecs for ASG just add the lb_listener_id to the AS config.
