### ISSUE TITLE
Propose to remove the unused releases 

### ISSUE THREAD

**Issue by freesky-edward** [huawei-clouds/terraform-provider-telefonicaopencloud#9]
### Expected Behavior
All releases will work well as the document descripted.

### Actual Behavior
the existing releases are all from OpenStack provider, they cannot run  well and it doesn't match the new document yet. 
it seems it is no reasonable to leave them as they were.  this issue is a proposal to remove them and make the new release plan. 

### references
[releases](https://github.com/huawei-clouds/terraform-provider-telefonicaopencloud/releases)  https://github.com/huawei-clouds/terraform-provider-telefonicaopencloud/releases

**Comment by niuzhenguo** [comment]
Done
